// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB476sTe3U6gHRIsQ3efivlxmF4My3F8p0',
    appId: '1:1097247260872:web:ccb1b40581250b746b65fd',
    messagingSenderId: '1097247260872',
    projectId: 'flutterchat-7d11b',
    authDomain: 'flutterchat-7d11b.firebaseapp.com',
    storageBucket: 'flutterchat-7d11b.appspot.com',
    measurementId: 'G-JLGTCPY97P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPW5SeYKXRzRqyxZZrs-0DBX1VKqE-v8U',
    appId: '1:1097247260872:android:39f3e325baa314d06b65fd',
    messagingSenderId: '1097247260872',
    projectId: 'flutterchat-7d11b',
    storageBucket: 'flutterchat-7d11b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKtTKiB1qKl8KCVr6vMVqRrt-aF71mUkw',
    appId: '1:1097247260872:ios:51a0111ff70099796b65fd',
    messagingSenderId: '1097247260872',
    projectId: 'flutterchat-7d11b',
    storageBucket: 'flutterchat-7d11b.appspot.com',
    iosBundleId: 'com.pablovaranaranjo.flutterchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB476sTe3U6gHRIsQ3efivlxmF4My3F8p0',
    appId: '1:1097247260872:web:d784084570c05ee56b65fd',
    messagingSenderId: '1097247260872',
    projectId: 'flutterchat-7d11b',
    authDomain: 'flutterchat-7d11b.firebaseapp.com',
    storageBucket: 'flutterchat-7d11b.appspot.com',
    measurementId: 'G-MKEK1H3CQW',
  );
}
